name: setup_simc

inputs:
  build-simc:
    required: false
    type: boolean
    default: true

outputs:
  cache-hit: ${{ steps.restore_cache.outputs.cache-hit }}

runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@v6
      id: clone_simc
      with:
        repository: simulationcraft/simc
        path: simc-profile/simc/

    - uses: actions/cache/restore@v5
      id: restore_cache
      continue-on-error: true
      with:
        path: simc-profile/simc/b/ninja/simc
        key: simc-clang++-18-cpp17-${{ steps.clone_simc.outputs.commit }}

    - uses: ./.github/workflows/build_simc
      if: ${{ !inputs.build-simc && steps.restore_cache.outputs.cache-hit != 'true' }}
      with:
        cache-key: ${{ steps.restore_cache.outputs.cache-primary-key }}
