name: build

on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          repository: simulationcraft/simc
          path: simc/

      - name: whereami
        run: |
          tree
          pwd

      - name: configure
        run: |
          cmake -H'${{ runner.workspace }}/simc-profile/simc/' -B'${{ runner.workspace }}/simc-profile/simc/b/ninja' -GNinja -DBUILD_GUI=OFF
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_CXX_COMPILER=clang++-18
          -DCMAKE_CXX_STANDARD=17
          -SC_NO_NETWORKING=ON

      - name: build
        run: |
          ninja -C '${{ runner.workspace }}/simc/b/ninja'

      - name: ident
        run: |
          cd '${{ runner.workspace }}/simc'
          git rev-parse HEAD

      - uses: actions/cache@v5
        with:
          path: ${{ runner.workspace }}/simc/b/ninja/simc
          key: simc-clang++-18-cpp17-${{ github.sha }}
