name: build

on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          repository: simulationcraft/simc

      - name: configure
        run: |
          cmake -H. \
          -B'${{ runner.workspace }}/b/ninja' -GNinja -DBUILD_GUI=OFF \
          -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++-18 \
          -DCMAKE_CXX_STANDARD=17 -DSC_NO_NETWORKING=ON

      - name: ident
        run: |
          echo "SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo $SHA
          echo ${{ env.SHA }}
          echo ${{ env.sha }}

      # - name: build
      #   run: |
      #     ninja -C '${{ runner.workspace }}/b/ninja'

      - uses: actions/cache@v5
        with:
          # path: ${{ runner.workspace }}/b/ninja/simc
          path: ${{ runner.workspace }}/README.md
          key: simc-clang++-18-cpp17-${{ env.sha }}
