name: ci

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  ci:
    runs-on: ubuntu-latest
    if: github.repository == 'simulationcraft/simc-profile' && github.ref_name == github.event.repository.default_branch

    steps:
      - uses: actions/checkout@v6

      - name: validate_seasonal_python_main
        run: |
          find ${{ runner.workspace }}/simc-profile/profiles -type f \
          | xargs python ${{ runner.workspace }}/simc-profile/scripts/validate.py \
          --validate-seasonal

      - uses: ./.github/workflows/setup_simc
        id: setup_simc

      - name: validate_simc_main
        if: ${{ steps.setup_simc.outputs.cache-hit != 'true' }}
        run: |
          find ${{ runner.workspace }}/simc-profile/profiles -type f \
          | xargs python ${{ runner.workspace }}/simc-profile/scripts/execute.py \
          -b ${{ runner.workspace }}/simc-profile/simc-profile/simc/b/ninja/simc \
          --save .

      - name: execute_simc_main
        if: ${{ steps.setup_simc.outputs.cache-hit != 'true' }}
        run: |
          find ${{ runner.workspace }}/simc-profile/profiles -type f \
          | xargs python ${{ runner.workspace }}/simc-profile/scripts/execute.py \
          -b ${{ runner.workspace }}/simc-profile/simc-profile/simc/b/ninja/simc \
          --execute .
