name: ci-pullrequest

on:
  pull_request

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: modified_files
        run: |
          files=$(git diff --diff-filter=AM --no-commit-id --name-only HEAD~1 -- '***.simc' | xargs)
          echo "MODIFIED_FILES=$files" >> $GITHUB_ENV

      - name: validate_python
        run: |
          python ${{ runner.workspace }}/simc-profile/scripts/validate.py \
          ${{ env.MODIFIED_FILES }} --validate

      - name: validate_seasonal_python
        if: github.event_name == 'pull_request'
        run: |
          python ${{ runner.workspace }}/simc-profile/scripts/validate.py \
          ${{ env.MODIFIED_FILES }} --validate-seasonal

      - uses: ./.github/workflows/setup_simc

      - name: validate_simc
        run: |
          python ${{ runner.workspace }}/simc-profile/scripts/execute.py \
          ${{ env.MODIFIED_FILES }} -b ${{ runner.workspace }}/simc-profile/simc-profile/simc/b/ninja/simc \
          --save .

      - name: execute_simc
        run: |
          python ${{ runner.workspace }}/simc-profile/scripts/execute.py \
          ${{ env.MODIFIED_FILES }} -b ${{ runner.workspace }}/simc-profile/simc-profile/simc/b/ninja/simc \
          --execute .
