name: CI

on: [pull_request, push]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          # path: ${{ runner.workspace }}/simc-profile/
          fetch-depth: 2

      - name: modified_files
        continue-on-error: true
        run: |
          # cd ${{ runner.workspace }}/simc-profile/
          files=$(git diff --diff-filter=AM --no-commit-id --name-only HEAD~1 -- '***.simc')
          echo $files
          if [[ -n "$files" ]]; then
            echo "MODIFIED_FILES=$files" >> $GITHUB_ENV
          else
            exit 1
          fi

      - name: validate_python
        run: |
          python ${{ runner.workspace }}/simc-profile/scripts/validate.py ${{ env.MODIFIED_FILES }}
          # python ${{ runner.workspace }}/scripts/validate.py ${{ env.MODIFIED_FILES }}

      - uses: ./.github/workflows/setup_simc.yml

      - name: validate_simc
        run: |
          python ${{ runner.workspace }}/simc-profile/scripts/execute.py ${{ env.MODIFIED_FILES }} -b ${{ runner.workspace }}/simc/b/ninja/simc --save /dev/null
          # python ${{ runner.workspace }}/scripts/execute.py ${{ env.MODIFIED_FILES }} -b ${{ runner.workspace }}/simc/b/ninja/simc --save /dev/null

      - name: execute_simc
        run: |
          python ${{ runner.workspace }}/simc-profile/scripts/execute.py ${{ env.MODIFIED_FILES }} -b ${{ runner.workspace }}/simc/b/ninja/simc --execute
          # python ${{ runner.workspace }}/scripts/execute.py ${{ env.MODIFIED_FILES }} -b ${{ runner.workspace }}/simc/b/ninja/simc --execute
