name: CI

on: [pull_request, push]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          path: ${{ runner.workspace }}/simc-profile/
          fetch-depth: 2

      - name: validate
        run: |
          tree
          cd ${{ runner.workspace }}/simc-profile/
          git diff-tree --no-commit-id --name-only HEAD -r

      # - uses: ./.github/workflows/setup_simc.yml
