name: CI

on: [pull_request, push]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          path: ${{ runner.workspace }}/simc-profile/
          fetch-depth: 2

      - name: modified_files
        continue-on-error: true
        run: |
          cd ${{ runner.workspace }}/simc-profile/
          git show --diff-filter=AM --no-commit-id --name-only HEAD
          files=$(git show --diff-filter=AM --no-commit-id --name-only HEAD -- '***.simc')
          echo $files
          echo $($files)
          if [[ -n "$files" ]]; then
            echo "MODIFIED_FILES=$files" >> $GITHUB_ENV
          else
            exit 1
          fi

      - name: validate
        # if: ${{ env.MODIFIED_FILES }} != ''
        run: |
          echo ${{ env.MODIFIED_FILES }}
          find ${{ runner.workspace }}/simc-profile/profiles -type f | xargs python ${{ runner.workspace }}/simc-profile/scripts/validate.py
          # python ${{ runner.workspace }}/simc-profile/scripts/validate.py ${{ env.MODIFIED_FILES }}

      # - uses: ./.github/workflows/setup_simc.yml
